const myShinyCollection = [
    // KANTO
    { id: 1, name: "Bulbasaur", region: "kanto", shiny: true, costume: false, count:1, type:"normal", gmax: false },
    { id: 2, name: "ivysaur", region: "kanto", count: 1, type: "normal" },
    { id: 4, name: "charmander", region: "kanto", count: 7, type: "normal" },
    { id: 6, name: "charizard", region: "kanto", count: 3, type: "normal" },
    { id: 7, name: "squirtle", region: "kanto", count: 14, type: "normal" },
    { id: 10, name: "caterpie", region: "kanto", count: 4, type: "normal" },
    { id: 12, name: "butterfree", displayName: "Butterfree", region: "kanto", count: 1, type: "normal" },
    { id: 12, name: "butterfree-costume", displayName: "Butterfree (Bow)", region: "kanto", count: 2, type: "costume" },
    { id: 13, name: "weedle", region: "kanto", count: 5, type: "normal" },
    { id: 14, name: "kakuna", region: "kanto", count: 1, type: "normal" },
    { id: 16, name: "pidgey", region: "kanto", count: 4, type: "normal" },
    { id: 18, name: "pidgeot", region: "kanto", count: 1, type: "normal" },
    { id: 19, name: "rattata", region: "kanto", count: 3, type: "normal" },
    { id: 21, name: "spearow", region: "kanto", count: 1, type: "normal" },
    { id: 23, name: "ekans", region: "kanto", count: 2, type: "normal" },
    { id: 25, name: "pikachu", region: "kanto", count: 6, type: "normal" },
    { id: 25, name: "pikachu-hat", displayName: "Pikachu (Top Hat)", region: "kanto", count: 1, type: "costume" },
    { id: 25, name: "pikachu-det", displayName: "Pikachu (Detective)", region: "kanto", count: 1, type: "costume" },
    { id: 26, name: "raichu-hat", displayName: "Raichu (Top Hat)", region: "kanto", count: 1, type: "costume" },
    { id: 27, name: "sandshrew", region: "kanto", count: 6, type: "normal" },
    { id: 27, name: "sandshrew-alola", displayName: "Sandshrew (Alola)", region: "kanto", count: 5, type: "normal" },
    { id: 29, name: "nidoran-f", region: "kanto", count: 3, type: "normal" },
    { id: 32, name: "nidoran-m", region: "kanto", count: 3, type: "normal" },
    { id: 35, name: "clefairy", region: "kanto", count: 6, type: "normal" },
    { id: 37, name: "vulpix", region: "kanto", count: 7, type: "normal" },
    { id: 37, name: "vulpix-alola", displayName: "Vulpix (Alola)", region: "kanto", count: 6, type: "normal" },
    { id: 39, name: "jigglypuff", region: "kanto", count: 2, type: "normal" },
    { id: 41, name: "zubat", region: "kanto", count: 1, type: "normal" },
    { id: 43, name: "oddish", region: "kanto", count: 2, type: "normal" },
    { id: 46, name: "paras", region: "kanto", count: 1, type: "normal" },
    { id: 50, name: "diglett", region: "kanto", count: 2, type: "normal" },
    { id: 50, name: "diglett-alola", displayName: "Diglett (Alola)", region: "kanto", count: 2, type: "normal" },
    { id: 52, name: "meowth", region: "kanto", count: 4, type: "normal" },
    { id: 52, name: "meowth-alola", displayName: "Meowth (Alola)", region: "kanto", count: 4, type: "normal" },
    { id: 52, name: "meowth-galar", displayName: "Meowth (Galar)", region: "kanto", count: 3, type: "normal" },
    { id: 53, name: "persian", region: "kanto", count: 1, type: "normal" },
    { id: 54, name: "psyduck", region: "kanto", count: 3, type: "normal" },
    { id: 55, name: "golduck", region: "kanto", count: 1, type: "normal" },
    { id: 56, name: "mankey", region: "kanto", count: 16, type: "normal" },
    { id: 58, name: "growlithe", region: "kanto", count: 3, type: "normal" },
    { id: 58, name: "growlithe-hisui", displayName: "Growlithe (Hisui)", region: "kanto", count: 3, type: "normal" },
    { id: 60, name: "poliwag", region: "kanto", count: 10, type: "normal" },
    { id: 63, name: "abra", region: "kanto", count: 3, type: "normal" },
    { id: 66, name: "machop", region: "kanto", count: 19, type: "normal" },
    { id: 69, name: "bellsprout", region: "kanto", count: 14, type: "normal" },
    { id: 71, name: "victreebel", region: "kanto", count: 2, type: "normal" },
    { id: 72, name: "tentacool", region: "kanto", count: 1, type: "normal" },
    { id: 73, name: "tentacruel", region: "kanto", count: 1, type: "normal" },
    { id: 74, name: "geodude", region: "kanto", count: 5, type: "normal" },
    { id: 74, name: "geodude-alola", displayName: "Geodude (Alola)", region: "kanto", count: 5, type: "normal" },
    { id: 76, name: "golem-alola", displayName: "Golem (Alola)", region: "kanto", count: 1, type: "normal" },
    { id: 77, name: "ponyta", region: "kanto", count: 9, type: "normal" },
    { id: 77, name: "ponyta-galar", displayName: "Ponyta (Galar)", region: "kanto", count: 8, type: "normal" },
    { id: 78, name: "rapidash-galar", displayName: "Rapidash (Galar)", region: "kanto", count: 2, type: "normal" },
    { id: 79, name: "slowpoke", region: "kanto", count: 6, type: "normal" },
    { id: 79, name: "slowpoke-galar", displayName: "Slowpoke (Galar)", region: "kanto", count: 6, type: "normal" },
    { id: 79, name: "slowpoke-hat", displayName: "Slowpoke (Hat)", region: "kanto", count: 4, type: "costume" },
    { id: 80, name: "slowbro", region: "kanto", count: 1, type: "normal" },
    { id: 81, name: "magnemite", region: "kanto", count: 4, type: "normal" },
    { id: 83, name: "farfetchd-galar", displayName: "Farfetch'd (Galar)", region: "kanto", count: 4, type: "normal" },
    { id: 84, name: "doduo", region: "kanto", count: 3, type: "normal" },
    { id: 85, name: "dodrio", region: "kanto", count: 1, type: "normal" },
    { id: 86, name: "seel", region: "kanto", count: 2, type: "normal" },
    { id: 88, name: "grimer", region: "kanto", count: 3, type: "normal" },
    { id: 88, name: "grimer-alola", displayName: "Grimer (Alola)", region: "kanto", count: 3, type: "normal" },
    { id: 90, name: "shellder", region: "kanto", count: 1, type: "normal" },
    { id: 92, name: "gastly", region: "kanto", count: 3, type: "normal" },
    { id: 94, name: "gengar", region: "kanto", count: 1, type: "normal" },
    { id: 95, name: "onix", region: "kanto", count: 8, type: "normal" },
    { id: 100, name: "voltorb", region: "kanto", count: 5, type: "normal" },
    { id: 100, name: "voltorb-hisui", displayName: "Voltorb (Hisui)", region: "kanto", count: 4, type: "normal" },
    { id: 102, name: "exeggcute", region: "kanto", count: 2, type: "normal" },
    { id: 103, name: "exeggutor-alola", displayName: "Exeggutor (Alola)", region: "kanto", count: 2, type: "normal" },
    { id: 104, name: "cubone", region: "kanto", count: 3, type: "normal" },
    { id: 105, name: "marowak-alola", displayName: "Marowak (Alola)", region: "kanto", count: 1, type: "normal" },
    { id: 106, name: "hitmonlee", region: "kanto", count: 4, type: "normal" },
    { id: 107, name: "hitmonchan", region: "kanto", count: 2, type: "normal" },
    { id: 108, name: "lickitung", region: "kanto", count: 13, type: "normal" },
    { id: 109, name: "koffing", region: "kanto", count: 6, type: "normal" },
    { id: 111, name: "rhyhorn", region: "kanto", count: 6, type: "normal" },
    { id: 113, name: "chansey", region: "kanto", count: 10, type: "normal" },
    { id: 113, name: "chansey-flower", displayName: "Chansey (Flower)", region: "kanto", count: 9, type: "costume" },
    { id: 114, name: "tangela", region: "kanto", count: 4, type: "normal" },
    { id: 115, name: "kangaskhan", region: "kanto", count: 2, type: "regional" },
    { id: 116, name: "horsea", region: "kanto", count: 2, type: "normal" },
    { id: 122, name: "mr-mime", region: "kanto", count: 2, type: "regional" },
    { id: 123, name: "scyther", region: "kanto", count: 5, type: "normal" },
    { id: 124, name: "jynx", region: "kanto", count: 2, type: "normal" },
    { id: 125, name: "electabuzz", region: "kanto", count: 5, type: "normal" },
    { id: 126, name: "magmar", region: "kanto", count: 4, type: "normal" },
    { id: 129, name: "magikarp", region: "kanto", count: 7, type: "normal" },
    { id: 130, name: "gyarados", region: "kanto", count: 1, type: "normal" },
    { id: 131, name: "lapras", region: "kanto", count: 3, type: "normal" },
    { id: 131, name: "lapras-scarf", displayName: "Lapras (Scarf)", region: "kanto", count: 2, type: "costume" },
    { id: 132, name: "ditto", region: "kanto", count: 7, type: "normal" },
    { id: 133, name: "eevee", region: "kanto", count: 8, type: "normal" },
    { id: 133, name: "eevee-hat", displayName: "Eevee (Party Hat)", region: "kanto", count: 5, type: "costume" },
    { id: 137, name: "porygon", region: "kanto", count: 9, type: "normal" },
    { id: 138, name: "omanyte", region: "kanto", count: 1, type: "normal" },
    { id: 142, name: "aerodactyl", region: "kanto", count: 1, type: "normal" },
    { id: 143, name: "snorlax", region: "kanto", count: 1, type: "normal" },
    { id: 147, name: "dratini", region: "kanto", count: 8, type: "normal" },
    { id: 149, name: "dragonite", region: "kanto", count: 2, type: "normal" },

    // JOHTO
    { id: 152, name: "chikorita", region: "johto", count: 1, type: "normal" },
    { id: 155, name: "cyndaquil", region: "johto", count: 21, type: "normal" },
    { id: 158, name: "totodile", region: "johto", count: 16, type: "normal" },
    { id: 161, name: "sentret", region: "johto", count: 3, type: "normal" },
    { id: 163, name: "hoothoot", region: "johto", count: 3, type: "normal" },
    { id: 163, name: "hoothoot-outfit", displayName: "Hoothoot (Outfit)", region: "johto", count: 2, type: "costume" },
    { id: 165, name: "ledyba", region: "johto", count: 1, type: "normal" },
    { id: 167, name: "spinarak", region: "johto", count: 6, type: "normal" },
    { id: 168, name: "ariados", region: "johto", count: 1, type: "normal" },
    { id: 170, name: "chinchou", region: "johto", count: 4, type: "normal" },
    { id: 171, name: "lanturn", region: "johto", count: 1, type: "normal" },
    { id: 172, name: "pichu", region: "johto", count: 1, type: "normal" },
    { id: 173, name: "cleffa", region: "johto", count: 4, type: "normal" },
    { id: 175, name: "togepi", region: "johto", count: 6, type: "normal" },
    { id: 176, name: "togetic", region: "johto", count: 15, type: "normal" },
    { id: 177, name: "natu", region: "johto", count: 4, type: "normal" },
    { id: 178, name: "xatu", region: "johto", count: 1, type: "normal" },
    { id: 179, name: "mareep", region: "johto", count: 16, type: "normal" },
    { id: 183, name: "marill", region: "johto", count: 6, type: "normal" },
    { id: 186, name: "politoed", region: "johto", count: 1, type: "normal" },
    { id: 187, name: "hoppip", region: "johto", count: 6, type: "normal" },
    { id: 190, name: "aipom", region: "johto", count: 1, type: "normal" },
    { id: 193, name: "yanma", region: "johto", count: 1, type: "normal" },
    { id: 194, name: "wooper", region: "johto", count: 7, type: "normal" },
    { id: 194, name: "wooper-paldea", displayName: "Wooper (Paldea)", region: "johto", count: 7, type: "normal" },
    { id: 196, name: "espeon", region: "johto", count: 2, type: "normal" },
    { id: 198, name: "murkrow", region: "johto", count: 5, type: "normal" },
    { id: 200, name: "misdreavus", region: "johto", count: 1, type: "normal" },
    { id: 202, name: "wobbuffet", region: "johto", count: 3, type: "normal" },
    { id: 204, name: "pineco", region: "johto", count: 5, type: "normal" },
    { id: 206, name: "dunsparce", region: "johto", count: 2, type: "normal" },
    { id: 207, name: "gligar", region: "johto", count: 6, type: "normal" },
    { id: 209, name: "snubbull", region: "johto", count: 4, type: "normal" },
    { id: 211, name: "qwilfish-hisui", displayName: "Qwilfish (Hisui)", region: "johto", count: 8, type: "normal" },
    { id: 212, name: "scizor", region: "johto", count: 1, type: "normal" },
    { id: 213, name: "shuckle", region: "johto", count: 1, type: "normal" },
    { id: 214, name: "heracross", region: "johto", count: 6, type: "regional" },
    { id: 215, name: "sneasel", region: "johto", count: 5, type: "normal" },
    { id: 215, name: "sneasel-hisui", displayName: "Sneasel (Hisui)", region: "johto", count: 5, type: "normal" },
    { id: 216, name: "teddiursa", region: "johto", count: 16, type: "normal" },
    { id: 217, name: "ursaring", region: "johto", count: 1, type: "normal" },
    { id: 218, name: "slugma", region: "johto", count: 3, type: "normal" },
    { id: 220, name: "swinub", region: "johto", count: 20, type: "normal" },
    { id: 225, name: "delibird", region: "johto", count: 2, type: "normal" },
    { id: 225, name: "delibird-ribbon", displayName: "Delibird (Ribbon)", region: "johto", count: 1, type: "costume" },
    { id: 226, name: "mantine", region: "johto", count: 3, type: "normal" },
    { id: 227, name: "skarmory", region: "johto", count: 4, type: "normal" },
    { id: 228, name: "houndour", region: "johto", count: 4, type: "normal" },
    { id: 231, name: "phanpy", region: "johto", count: 1, type: "normal" },
    { id: 235, name: "smeargle", region: "johto", count: 2, type: "normal" },
    { id: 236, name: "tyrogue", region: "johto", count: 4, type: "normal" },
    { id: 237, name: "hitmontop", region: "johto", count: 2, type: "normal" },
    { id: 238, name: "elekid", region: "johto", count: 4, type: "normal" },
    { id: 239, name: "magby", region: "johto", count: 2, type: "normal" },
    { id: 242, name: "blissey", region: "johto", count: 1, type: "normal" },
    { id: 246, name: "larvitar", region: "johto", count: 13, type: "normal" },
    { id: 248, name: "tyranitar", region: "johto", count: 1, type: "normal" },

    // HOENN
    { id: 249, name: "lugia", region: "hoenn", count: 1, type: "normal" },
    { id: 250, name: "ho-oh", region: "hoenn", count: 2, type: "normal" },
    { id: 252, name: "treecko", region: "hoenn", count: 4, type: "normal" },
    { id: 254, name: "sceptile", region: "hoenn", count: 1, type: "normal" },
    { id: 255, name: "torchic", region: "hoenn", count: 2, type: "normal" },
    { id: 257, name: "blaziken", region: "hoenn", count: 2, type: "normal" },
    { id: 258, name: "mudkip", region: "hoenn", count: 12, type: "normal" },
    { id: 259, name: "marshtomp", region: "hoenn", count: 2, type: "normal" },
    { id: 261, name: "poochyena", region: "hoenn", count: 3, type: "normal" },
    { id: 262, name: "mightyena", region: "hoenn", count: 1, type: "normal" },
    { id: 263, name: "zigzagoon-galar", displayName: "Zigzagoon (Galar)", region: "hoenn", count: 17, type: "normal" },
    { id: 270, name: "lotad", region: "hoenn", count: 3, type: "normal" },
    { id: 273, name: "seedot", region: "hoenn", count: 5, type: "normal" },
    { id: 274, name: "nuzleaf", region: "hoenn", count: 1, type: "normal" },
    { id: 276, name: "taillow", region: "hoenn", count: 2, type: "normal" },
    { id: 278, name: "wingull", region: "hoenn", count: 2, type: "normal" },
    { id: 279, name: "pelipper", region: "hoenn", count: 1, type: "normal" },
    { id: 280, name: "ralts", region: "hoenn", count: 8, type: "normal" },
    { id: 281, name: "kirlia", region: "hoenn", count: 2, type: "normal" },
    { id: 283, name: "surskit", region: "hoenn", count: 3, type: "normal" },
    { id: 285, name: "shroomish", region: "hoenn", count: 1, type: "normal" },
    { id: 287, name: "slakoth", region: "hoenn", count: 2, type: "normal" },
    { id: 287, name: "slakoth-visor", displayName: "Slakoth (Visor)", region: "hoenn", count: 1, type: "costume" },
    { id: 290, name: "nincada", region: "hoenn", count: 1, type: "normal" },
    { id: 296, name: "makuhita", region: "hoenn", count: 1, type: "normal" },
    { id: 299, name: "nosepass", region: "hoenn", count: 4, type: "normal" },
    { id: 300, name: "skitty", region: "hoenn", count: 4, type: "normal" },
    { id: 302, name: "sableye", region: "hoenn", count: 4, type: "normal" },
    { id: 303, name: "mawile", region: "hoenn", count: 6, type: "normal" },
    { id: 304, name: "aron", region: "hoenn", count: 4, type: "normal" },
    { id: 306, name: "aggron", region: "hoenn", count: 1, type: "normal" },
    { id: 307, name: "meditite", region: "hoenn", count: 6, type: "normal" },
    { id: 309, name: "electrike", region: "hoenn", count: 7, type: "normal" },
    { id: 312, name: "minun", region: "hoenn", count: 1, type: "normal" },
    { id: 313, name: "volbeat", region: "hoenn", count: 3, type: "regional" },
    { id: 314, name: "illumise", region: "hoenn", count: 1, type: "regional" },
    { id: 315, name: "roselia", region: "hoenn", count: 7, type: "normal" },
    { id: 316, name: "gulpin", region: "hoenn", count: 3, type: "normal" },
    { id: 317, name: "swalot", region: "hoenn", count: 1, type: "normal" },
    { id: 318, name: "carvanha", region: "hoenn", count: 2, type: "normal" },
    { id: 319, name: "sharpedo", region: "hoenn", count: 3, type: "normal" },
    { id: 320, name: "wailmer", region: "hoenn", count: 3, type: "normal" },
    { id: 322, name: "numel", region: "hoenn", count: 2, type: "normal" },
    { id: 323, name: "camerupt", region: "hoenn", count: 3, type: "normal" },
    { id: 325, name: "spoink", region: "hoenn", count: 3, type: "normal" },
    { id: 327, name: "spinda", region: "hoenn", count: 1, type: "normal" },
    { id: 328, name: "trapinch", region: "hoenn", count: 8, type: "normal" },
    { id: 330, name: "flygon", region: "hoenn", count: 1, type: "normal" },
    { id: 331, name: "cacnea", region: "hoenn", count: 6, type: "normal" },
    { id: 333, name: "swablu", region: "hoenn", count: 17, type: "normal" },
    { id: 335, name: "zangoose", region: "hoenn", count: 2, type: "regional" },
    { id: 337, name: "lunatone", region: "hoenn", count: 6, type: "regional" },
    { id: 338, name: "solrock", region: "hoenn", count: 6, type: "regional" },
    { id: 340, name: "barboach", region: "hoenn", count: 1, type: "normal" },
    { id: 341, name: "corphish", region: "hoenn", count: 5, type: "normal" },
    { id: 343, name: "baltoy", region: "hoenn", count: 3, type: "normal" },
    { id: 347, name: "anorith", region: "hoenn", count: 1, type: "normal" },
    { id: 349, name: "feebas", region: "hoenn", count: 6, type: "normal" },
    { id: 351, name: "castform", region: "hoenn", count: 4, type: "normal" },
    { id: 351, name: "castform-rainy", displayName: "Castform (Rainy)", region: "hoenn", count: 3, type: "normal" },
    { id: 353, name: "shuppet", region: "hoenn", count: 4, type: "normal" },
    { id: 355, name: "duskull", region: "hoenn", count: 12, type: "normal" },
    { id: 355, name: "duskull-flower", displayName: "Duskull (Flower)", region: "hoenn", count: 12, type: "costume" },
    { id: 356, name: "dusclops", region: "hoenn", count: 2, type: "normal" },
    { id: 358, name: "chimecho", region: "hoenn", count: 2, type: "normal" },
    { id: 359, name: "absol", region: "hoenn", count: 2, type: "normal" },
    { id: 359, name: "absol-glasses", displayName: "Absol (Glasses)", region: "hoenn", count: 2, type: "costume" },
    { id: 363, name: "spheal", region: "hoenn", count: 5, type: "normal" },
    { id: 363, name: "spheal-scarf", displayName: "Spheal (Scarf)", region: "hoenn", count: 4, type: "costume" },
    { id: 366, name: "clamperl", region: "hoenn", count: 4, type: "normal" },
    { id: 367, name: "huntail", region: "hoenn", count: 1, type: "normal" },
    { id: 370, name: "luvdisc", region: "hoenn", count: 5, type: "normal" },
    { id: 371, name: "bagon", region: "hoenn", count: 18, type: "normal" },
    { id: 374, name: "beldum", region: "hoenn", count: 17, type: "normal" },
    { id: 383, name: "groudon", region: "hoenn", count: 1, type: "normal" },

    // SINNOH
    { id: 387, name: "turtwig", region: "sinnoh", count: 3, type: "normal" },
    { id: 390, name: "chimchar", region: "sinnoh", count: 1, type: "normal" },
    { id: 393, name: "piplup", region: "sinnoh", count: 11, type: "normal" },
    { id: 395, name: "empoleon", region: "sinnoh", count: 1, type: "normal" },
    { id: 396, name: "starly", region: "sinnoh", count: 22, type: "normal" },
    { id: 397, name: "staravia", region: "sinnoh", count: 1, type: "normal" },
    { id: 399, name: "bidoof", region: "sinnoh", count: 4, type: "normal" },
    { id: 401, name: "kricketot", region: "sinnoh", count: 7, type: "normal" },
    { id: 403, name: "shinx", region: "sinnoh", count: 7, type: "normal" },
    { id: 403, name: "shinx-hat", displayName: "Shinx (Top Hat)", region: "sinnoh", count: 6, type: "costume" },
    { id: 408, name: "cranidos", region: "sinnoh", count: 3, type: "normal" },
    { id: 410, name: "shieldon", region: "sinnoh", count: 3, type: "normal" },
    { id: 412, name: "burmy-trash", displayName: "Burmy (Trash)", region: "sinnoh", count: 2, type: "normal" },
    { id: 415, name: "combee", region: "sinnoh", count: 6, type: "normal" },
    { id: 417, name: "pachirisu", region: "sinnoh", count: 2, type: "regional" },
    { id: 418, name: "buizel", region: "sinnoh", count: 4, type: "normal" },
    { id: 422, name: "shellos-east", displayName: "Shellos (East Sea)", region: "sinnoh", count: 1, type: "regional" },
    { id: 425, name: "drifloon", region: "sinnoh", count: 1, type: "normal" },
    { id: 427, name: "buneary", region: "sinnoh", count: 6, type: "normal" },
    { id: 428, name: "lopunny", region: "sinnoh", count: 1, type: "normal" },
    { id: 431, name: "glameow", region: "sinnoh", count: 1, type: "normal" },
    { id: 436, name: "bronzor", region: "sinnoh", count: 9, type: "normal" },
    { id: 437, name: "bronzong", region: "sinnoh", count: 1, type: "normal" },
    { id: 438, name: "bonsly", region: "sinnoh", count: 3, type: "normal" },
    { id: 439, name: "mime-jr", region: "sinnoh", count: 2, type: "normal" },
    { id: 440, name: "happiny", region: "sinnoh", count: 3, type: "normal" },
    { id: 443, name: "gible", region: "sinnoh", count: 23, type: "normal" },
    { id: 445, name: "garchomp", region: "sinnoh", count: 2, type: "normal" },
    { id: 446, name: "munchlax", region: "sinnoh", count: 6, type: "normal" },
    { id: 451, name: "skorupi", region: "sinnoh", count: 3, type: "normal" },
    { id: 452, name: "drapion", region: "sinnoh", count: 1, type: "normal" },
    { id: 453, name: "croagunk", region: "sinnoh", count: 2, type: "normal" },
    { id: 453, name: "croagunk-hat", displayName: "Croagunk (Hat)", region: "sinnoh", count: 2, type: "costume" },
    { id: 454, name: "toxicroak", region: "sinnoh", count: 1, type: "normal" },
    { id: 459, name: "snover", region: "sinnoh", count: 5, type: "normal" },
    { id: 466, name: "electivire", region: "sinnoh", count: 1, type: "normal" },
    { id: 467, name: "magmortar", region: "sinnoh", count: 2, type: "normal" },
    { id: 472, name: "gliscor", region: "sinnoh", count: 1, type: "normal" },
    { id: 474, name: "porygon-z", region: "sinnoh", count: 1, type: "normal" },
    { id: 475, name: "gallade", region: "sinnoh", count: 5, type: "normal" },
    { id: 478, name: "froslass", region: "sinnoh", count: 1, type: "normal" },
    { id: 480, name: "azelf", region: "sinnoh", count: 1, type: "regional" },
    { id: 484, name: "palkia-origin", displayName: "Palkia (Origin)", region: "sinnoh", count: 6, type: "background" },
    { id: 488, name: "cresselia", region: "sinnoh", count: 1, type: "normal" },

    // UNOVA
    { id: 495, name: "snivy", region: "unova", count: 16, type: "normal" },
    { id: 498, name: "tepig", region: "unova", count: 14, type: "normal" },
    { id: 500, name: "emboar", region: "unova", count: 1, type: "normal" },
    { id: 501, name: "oshawott", region: "unova", count: 9, type: "normal" },
    { id: 503, name: "samurott", region: "unova", count: 1, type: "normal" },
    { id: 503, name: "samurott-hisui", displayName: "Samurott (Hisui)", region: "unova", count: 1, type: "normal" },
    { id: 524, name: "roggenrola", region: "unova", count: 13, type: "normal" },
    { id: 532, name: "timburr", region: "unova", count: 16, type: "normal" },
    { id: 534, name: "conkeldurr", region: "unova", count: 1, type: "normal" },
    { id: 540, name: "sewaddle", region: "unova", count: 10, type: "normal" },
    { id: 543, name: "venipede", region: "unova", count: 9, type: "normal" },
    { id: 546, name: "cottonee", region: "unova", count: 6, type: "normal" },
    { id: 562, name: "yamask", region: "unova", count: 8, type: "normal" },
    { id: 562, name: "yamask-galar", displayName: "Yamask (Galar)", region: "unova", count: 8, type: "normal" },
    { id: 577, name: "solosis", region: "unova", count: 16, type: "normal" },
    { id: 587, name: "emolga", region: "unova", count: 7, type: "normal" },
    { id: 607, name: "litwick", region: "unova", count: 19, type: "normal" },
    { id: 610, name: "axew", region: "unova", count: 4, type: "normal" },
    { id: 616, name: "shelmet", region: "unova", count: 7, type: "normal" },
    { id: 622, name: "golett", region: "unova", count: 5, type: "normal" },
    { id: 633, name: "deino", region: "unova", count: 17, type: "normal" },
    { id: 639, name: "terrakion", region: "unova", count: 1, type: "normal" },
    { id: 643, name: "reshiram", region: "unova", count: 1, type: "normal" },
    { id: 646, name: "kyurem", region: "unova", count: 3, type: "normal" },

    // KALOS
    { id: 650, name: "chespin", region: "kalos", count: 16, type: "normal" },
    { id: 653, name: "fennekin", region: "kalos", count: 14, type: "normal" },
    { id: 656, name: "froakie", region: "kalos", count: 16, type: "normal" },
    { id: 686, name: "inkay", region: "kalos", count: 10, type: "normal" },
    { id: 704, name: "goomy", region: "kalos", count: 22, type: "normal" },
    { id: 714, name: "noibat", region: "kalos", count: 22, type: "normal" },
    { id: 716, name: "xerneas", region: "kalos", count: 2, type: "normal" },

    // ALOLA
    { id: 722, name: "rowlet", region: "alola", count: 14, type: "normal" },
    { id: 725, name: "litten", region: "alola", count: 17, type: "normal" },
    { id: 728, name: "popplio", region: "alola", count: 16, type: "normal" },
    { id: 736, name: "grubbin", region: "alola", count: 13, type: "normal" },
    { id: 765, name: "oranguru", region: "alola", count: 11, type: "normal" },
    { id: 766, name: "passimian", region: "alola", count: 3, type: "normal" },
    { id: 782, name: "jangmo-o", region: "alola", count: 16, type: "normal" },

    // GALAR
    { id: 810, name: "grookey", region: "galar", count: 16, type: "normal" },
    { id: 813, name: "scorbunny", region: "galar", count: 11, type: "normal" },
    { id: 819, name: "skwovet", region: "galar", count: 6, type: "normal" },

    // PALDEA
    { id: 906, name: "sprigatito", region: "paldea", count: 16, type: "normal" },
    { id: 909, name: "fuecoco", region: "paldea", count: 14, type: "normal" },
    { id: 912, name: "quaxly", region: "paldea", count: 16, type: "normal" },
    { id: 915, name: "lechonk", region: "paldea", count: 6, type: "normal" },
    { id: 921, name: "pawmi", region: "paldea", count: 11, type: "normal" },
    { id: 928, name: "smoliv", region: "paldea", count: 6, type: "normal" },
    { id: 957, name: "tinkatink", region: "paldea", count: 16, type: "normal" },
    { id: 959, name: "tinkataton", region: "paldea", count: 2, type: "normal" },
    { id: 447, name: "riolu", region: "paldea", count: 10, type: "normal" },
    { id: 793, name: "nihilego", region: "paldea", count: 2, type: "normal" }
];
